### ISSUE TITLE
Loading Facts...

### ISSUE THREAD

**Issue by joshcoen** [emccode/vagrant-puppet-scaleio#1]
Getting an error after the tiebreaker is deployed when puppet tries to load facts.

![loading_facts](https://cloud.githubusercontent.com/assets/6854635/6466735/bfc8359e-c197-11e4-9267-4f17de6b92df.PNG)

When I SSH'd to the tb machine there was no directories/files under /etc/puppet/modules

**Comment by virtualswede** [comment]
Hi Josh,

Thanks for letting us know about this issue.
This is in relation to this: https://github.com/emccode/puppet-scaleio/pull/5

There will be a new module pushed to the Forge later today, we'll update when it's done.

**Comment by joshcoen** [comment]
Thanks Jonas!

**Comment by clintonskitson** [comment]
Module fixed with release of puppet-scaleio v0.1.3. Thanks Josh!
